# Generated by Django 3.0.4 on 2020-05-15 07:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=' ', null=True)),
                ('image', models.ImageField(blank=True, upload_to='post_image')),
                ('tags', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 32, 6, 158605))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=255)),
                ('body', models.TextField(default='', max_length=255)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 32, 6, 158605))),
                ('forum', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.Forum')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
