# Generated by Django 3.0.7 on 2020-07-03 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemStatements', '0011_auto_20200609_2143'),
        ('articles', '0007_auto_20200702_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problemStatements.Discussion'),
        ),
    ]
