# Generated by Django 3.0.4 on 2020-05-15 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 32, 6, 158605))),
                ('updatedDate', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 32, 6, 158605))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='accounts.Student')),
            ],
        ),
    ]
