# Generated by Django 3.0.4 on 2020-05-15 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 21, 23, 17, 10117)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 21, 23, 17, 10117)),
        ),
    ]
