# Generated by Django 3.0.4 on 2020-05-15 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('topic', models.CharField(blank=True, choices=[('POINTERS', 'POINTERS'), ('ARRAYS', 'ARRAYS'), ('STRINGS', 'STRINGS'), ('HASHMAPS', 'HASHMAPS'), ('SORTING', 'SORTING'), ('RECURSION', 'RECURSION'), ('BACKTRACKING', 'BACKTRACKING'), ('STACKSANDQUEUES', 'STACKANDQUEUES'), ('LINKEDLISTS', 'LINKEDLISTS'), ('TREES', 'TREES'), ('GREEDY', 'GREEDY'), ('DYNAMICPROGRAMMING', 'DYNAMICPROGRAMMING'), ('GRAPHS', 'GRAPHS')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, default=' ', null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=6, null=True)),
                ('content', models.TextField(blank=True, default=' ', null=True)),
                ('instream', models.TextField(blank=True, default=' ', null=True)),
                ('outstream', models.TextField(blank=True, default=' ', null=True)),
                ('timeConstraint', models.CharField(blank=True, max_length=100, null=True)),
                ('spaceConstraint', models.CharField(blank=True, max_length=12, null=True)),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 32, 6, 122353))),
                ('updatedDate', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 32, 6, 122353))),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.TextField(blank=True, default=' ', null=True)),
                ('Output', models.TextField(blank=True, default=' ', null=True)),
                ('problemStatement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='problemStatements.ProblemStatement')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('timeTakenMillis', models.CharField(blank=True, max_length=100, null=True)),
                ('spaceTakenBytes', models.CharField(blank=True, max_length=12, null=True)),
                ('language', models.CharField(blank=True, choices=[('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java')], max_length=15, null=True)),
                ('problemStatement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problemStatements.ProblemStatement')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
