# Generated by Django 3.0.4 on 2020-05-15 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemStatements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('createdDate', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 21, 23, 17, 6082)),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 21, 23, 17, 6082)),
        ),
    ]
