# Generated by Django 3.0.4 on 2020-05-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('problemStatements', '0003_auto_20200515_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='problemStatement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='problemStatements.ProblemStatement'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
