# Generated by Django 3.0.4 on 2020-05-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('problemStatements', '0004_auto_20200515_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='problemStatement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='problemStatements.ProblemStatement'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='accounts.Student'),
        ),
    ]
