# Generated by Django 3.0.4 on 2020-05-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('problemStatements', '0005_auto_20200517_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='accounts.Student'),
        ),
    ]
