# Generated by Django 3.0.4 on 2020-05-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemStatements', '0007_auto_20200527_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problemStatement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problemStatements.ProblemStatement'),
        ),
    ]
