# Generated by Django 3.0.4 on 2020-06-09 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemStatements', '0008_auto_20200527_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
