# Generated by Django 3.0.4 on 2020-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemStatements', '0010_auto_20200609_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
