# Generated by Django 3.0.7 on 2020-07-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemStatements', '0011_auto_20200609_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='testInput',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='testOutput',
            field=models.TextField(blank=True, null=True),
        ),
    ]
